##
## Note that BLOCK_IP_FRAG_OVERLAP will always *block* fragmented IP datagrams of which
## the fragments are overlapping.. 
##

CC=gcc
CFLAGS=  -D_THREAD_SAFE -I/usr/local/include/pthread/linuxthreads -llthread -llgcc_r -Wall -lcurses -llinkedlist -lpcap  -DWITH_SYSLOG -DBLOCK_IP_FRAG_OVERLAP
#SRCS= log.c util.c pcap.c signature.c ip.c
SRCS= log.c util.c pcap.c signature.c ip2.c

all:   
	cd llist && make -f Makefile.lthread
	${CC} -g -I. -L. -I ./llist -I ./includes -L ./llist ${CFLAGS} -o pcap ${SRCS}

debug:   
	cd llist && make debug
	${CC} -g -DWITH_DEBUG -I. -L. -I ./llist -I ./includes -L ./llist ${CFLAGS} -o pcap ${SRCS}

clean:
	rm -f pcap *.o *.a tests/*.o tests/*.core *.core *.o *.so

dist: clean
	cd .. && tar -zcvf IDS.tgz IDS


